general {
    col.active_border = 0xffc4a7e7
    col.inactive_border = 0xaa403d52
}

misc {
    background_color = 0xff191724
}

plugin {
    hyprbars {
        bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = 0xff191724
        col.text = 0xffe0def4


        hyprbars-button = rgb(224, 222, 244), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(224, 222, 244), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(224, 222, 244), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrulev2 = bordercolor 0xaaeb6f92 0x77eb6f92,pinned:1
